<a href="https://colab.research.google.com/github/agranadmorera/My-Stuff/blob/main/Practica_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
test_score_1 = (68,96,71)
test_score_2 = (92,87,83)

test_score = test_score_1 + test_score_2
test_score

(68, 96, 71, 92, 87, 83)

In [ ]:
country_list_1 = ['Angola','Uzbekistan','China','Brazil','Mexico']
country_list_2 = ['Serbia','Turkey','Fiji']

country_list_final = country_list_1 + country_list_2
country_list_final

['Angola',
 'Uzbekistan',
 'China',
 'Brazil',
 'Mexico',
 'Serbia',
 'Turkey',
 'Fiji']

In [ ]:
first_name = 'Chita'
last_name = 'Umbawa'

full_name = first_name+' '+last_name
full_name

'Chita Umbawa'

In [ ]:
age = (12,17,9) * 3
age

(12, 17, 9, 12, 17, 9, 12, 17, 9)

In [ ]:
ID = [101,23,77,45] * 2
ID

[101, 23, 77, 45, 101, 23, 77, 45]

In [ ]:
name = 'friend'*3
name

'friendfriendfriend'

In [ ]:
lepra = 5 ** 3
lepra

125

In [ ]:
def add_two_numbers(num1, num2) :
    return num1 + num2

number1 = 23
number2 = 47.5
result = add_two_numbers(number1,number2)
result

70.5

In [ ]:
def profile() :
    age = 21
    height = 5.5
    weight = 130
    return age, height, weight

age, height, weight = profile()

In [ ]:
print(age, height, weight)

21 5.5 130


In [ ]:
store_list = ['Muerta de Hambre','Cevichera','Soda del Mercado','Taco Bell','Burger King']

for position, name in enumerate(store_list):
    print(position, name)

0 Muerta de Hambre
1 Cevichera
2 Soda del Mercado
3 Taco Bell
4 Burger King


In [ ]:
store_map = dict((name, position) for position, name in enumerate(store_list))
store_map

{'Burger King': 4,
 'Cevichera': 1,
 'Muerta de Hambre': 0,
 'Soda del Mercado': 2,
 'Taco Bell': 3}

In [16]:
distance = [10, 15, 17, 26]
time = [.30, .47, .55, 1.20]

import numpy as np

np_distance = np.array(distance)
np_time = np.array(time)
speed = np_distance/np_time
speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [20]:
#first NumPy array
first_numpy_array = np.array([1,2,3,4])
print(first_numpy_array)

[1 2 3 4]


In [21]:
#array with zeros
array_with_zeros = np.zeros((3,3))
array_with_zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [22]:
#array with ones
array_with_ones = np.ones((3,3))
array_with_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [23]:
#array with empty
array_with_empty = np.empty((2,3))
array_with_empty

array([[4.63920264e-310, 0.00000000e+000, 0.00000000e+000],
       [0.00000000e+000, 0.00000000e+000, 0.00000000e+000]])

In [25]:
#array with arange method
np_arange = np.arange(12)
print(np_arange)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
#reshape method to change/ create array
np_arange.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [27]:
#linspace for linearly (equal) spaced data elements
np_linspace = np.linspace(1,6,5)
print(np_linspace)

[1.   2.25 3.5  4.75 6.  ]


In [29]:
#One dimensional array
oneD_array = np.arange(15)
print(oneD_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [33]:
#Two dimensional array
TwoD_array = oneD_array.reshape(3,5)
print(TwoD_array)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


In [34]:
np_linspace = np.linspace(4,13,7)
print(np_linspace)

[ 4.   5.5  7.   8.5 10.  11.5 13. ]
