<a href="https://colab.research.google.com/github/agranadmorera/Test2/blob/main/Practica_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
first_trial_cyclist = [10,15,17,26]
second_trial_cyclist = [12,11,21,24]
np_first_trial_cyclist = np.array(first_trial_cyclist)
np_second_trial_cyclist = np.array(second_trial_cyclist)
np_first_trial_cyclist+np_second_trial_cyclist

array([22, 26, 38, 50])

In [ ]:
import numpy as np

In [ ]:
#addition
np.add(45,20)

65

In [ ]:
#substraction
np.subtract(49,23)

26

In [ ]:
# ndarray multiplication
# create ndarray which contains number of hrs worked for 5 days
# hourly rate is 15 USD
np_daily_wage = np.array([7,9,13,8,11])*15

In [ ]:
#print hourly wage for each day
print(np_daily_wage)

[105 135 195 120 165]


In [ ]:
#total earning after 5 days
#use sum method to add all data elements of ndarray
sum(np_daily_wage)

720

In [ ]:
#comparison operations
#create ndarray for weekly hrs, 5 consecutive weeks hrs data
#np_weekly_hrs = np.array([23,41,55,47,38])

In [ ]:
#week with more than 40 hrs
np_weekly_hrs[np_weekly_hrs>40]

array([41, 55, 47])

In [ ]:
#Logical AND operation
np.logical_and(np_weekly_hrs>20,np_weekly_hrs<50)

array([ True,  True, False,  True,  True])

In [ ]:
#Logical NOT operatin
np.logical_not(np_weekly_hrs>35)

array([ True, False, False, False, False])

In [ ]:
cyclist_trials = np.array([[10,15,17,26],[12,11,21,24]])

In [ ]:
first_trial = cyclist_trials[0]

In [ ]:
first_trial

array([10, 15, 17, 26])

In [ ]:
second_trial = cyclist_trials[1]
second_trial

array([12, 11, 21, 24])