In [1]:
import LinearAlgebra as la #or
import LinearAlgebra
const LinearAlgebra = la

LinearAlgebra

In [6]:
import Pkg; Pkg.add("Animations")

    Updating registry at `C:\Users\cgranados\.julia\registries\General.toml`
   Resolving package versions...
   Installed Animations ─ v0.4.1
    Updating `C:\Users\cgranados\.julia\environments\v1.7\Project.toml`
  [27a7e980] + Animations v0.4.1
    Updating `C:\Users\cgranados\.julia\environments\v1.7\Manifest.toml`
  [27a7e980] + Animations v0.4.1
Precompiling project...
  ✓ Animations
  1 dependency successfully precompiled in 5 seconds (199 already precompiled)


In [8]:
import Pkg; Pkg.add("Javis")

   Resolving package versions...
   Installed gdk_pixbuf_jll ─ v2.42.6+1
   Installed Librsvg_jll ──── v2.52.4+0
   Installed Media ────────── v0.5.0
   Installed Pango_jll ────── v1.50.3+0
   Installed Graphics ─────── v1.1.2
   Installed Rsvg ─────────── v1.0.0
   Installed LightXML ─────── v0.9.0
   Installed Juno ─────────── v0.8.4
   Installed Cairo ────────── v1.0.5
   Installed Javis ────────── v0.1.5
   Installed Luxor ────────── v2.19.0
    Updating `C:\Users\cgranados\.julia\environments\v1.7\Project.toml`
  [78b212ba] + Javis v0.1.5
    Updating `C:\Users\cgranados\.julia\environments\v1.7\Manifest.toml`
  [159f3aea] + Cairo v1.0.5
  [a2bd30eb] + Graphics v1.1.2
  [78b212ba] + Javis v0.1.5
  [e5e0dc1b] + Juno v0.8.4
  [9c8b4983] + LightXML v0.9.0
  [ae8d54c2] + Luxor v2.19.0
  [e89f7d12] + Media v0.5.0
  [c4c386cf] + Rsvg v1.0.0
  [925c91fb] + Librsvg_jll v2.52.4+0
  [36c8627f] + Pango_jll v1.50.3+0
  [da03df04] + gdk_pixbuf_jll v2.42.6+1
  [9abbd945] + Profile
Precompiling 

In [9]:
import Pkg; Pkg.add("Unitful")
import Pkg; Pkg.add("PeriodicTable")

   Resolving package versions...
   Installed ConstructionBase ─ v1.4.0
   Installed Unitful ────────── v1.11.0
    Updating `C:\Users\cgranados\.julia\environments\v1.7\Project.toml`
  [1986cc42] + Unitful v1.11.0
    Updating `C:\Users\cgranados\.julia\environments\v1.7\Manifest.toml`
  [187b0558] + ConstructionBase v1.4.0
  [1986cc42] + Unitful v1.11.0
Precompiling project...
  ✓ ConstructionBase
  ✓ Unitful
  2 dependencies successfully precompiled in 23 seconds (211 already precompiled)
   Resolving package versions...
   Installed PeriodicTable ─ v1.1.2
    Updating `C:\Users\cgranados\.julia\environments\v1.7\Project.toml`
  [7b2266bf] + PeriodicTable v1.1.2
    Updating `C:\Users\cgranados\.julia\environments\v1.7\Manifest.toml`
  [7b2266bf] + PeriodicTable v1.1.2
Precompiling project...
  ✓ PeriodicTable
  1 dependency successfully precompiled in 4 seconds (213 already precompiled)


In [10]:
using Animations
using Javis
using PeriodicTable
using Unitful

In [13]:
a = zeros(Int64,10)

10-element Vector{Int64}:
 0
 0
 0
 0
 0
 0
 0
 0
 0
 0

In [14]:
sizeof(a)
length(a)*sizeof(eltype(a))

80

In [15]:
?zeros

search: zeros count_zeros set_zero_subnormals get_zero_subnormals leading_zeros



```
zeros([T=Float64,] dims::Tuple)
zeros([T=Float64,] dims...)
```

Create an `Array`, with element type `T`, of all zeros with size specified by `dims`. See also [`fill`](@ref), [`ones`](@ref), [`zero`](@ref).

# Examples

```jldoctest
julia> zeros(1)
1-element Vector{Float64}:
 0.0

julia> zeros(Int8, 2, 3)
2×3 Matrix{Int8}:
 0  0  0
 0  0  0
```


In [16]:
a = zeros(Int,10)
a[5] = 1

1

In [17]:
a = [10:49;]
a = collect(10:49)

40-element Vector{Int64}:
 10
 11
 12
 13
 14
 15
 16
 17
 18
 19
 20
 21
 22
  ⋮
 38
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49

In [18]:
a[end:-1:1] #faster
reverse(a)
reverse!(a) #inplace

40-element Vector{Int64}:
 49
 48
 47
 46
 45
 44
 43
 42
 41
 40
 39
 38
 37
  ⋮
 21
 20
 19
 18
 17
 16
 15
 14
 13
 12
 11
 10

In [19]:
a = reshape(0:8,3,3)

3×3 reshape(::UnitRange{Int64}, 3, 3) with eltype Int64:
 0  3  6
 1  4  7
 2  5  8

In [26]:
a = reshape(0:11,3,4)

3×4 reshape(::UnitRange{Int64}, 3, 4) with eltype Int64:
 0  3  6   9
 1  4  7  10
 2  5  8  11

In [20]:
findall(!isequal(0),a)
findall(!iszero,a)
findall(!=(0),a)

8-element Vector{CartesianIndex{2}}:
 CartesianIndex(2, 1)
 CartesianIndex(3, 1)
 CartesianIndex(1, 2)
 CartesianIndex(2, 2)
 CartesianIndex(3, 2)
 CartesianIndex(1, 3)
 CartesianIndex(2, 3)
 CartesianIndex(3, 3)

In [21]:
using LinearAlgebra
a = I(3)
a = Matrix(1.0I,3,3)

3×3 Matrix{Float64}:
 1.0  0.0  0.0
 0.0  1.0  0.0
 0.0  0.0  1.0

In [22]:
a = rand(3,3,3) #numbers in the range 0 to 1
b = randn(3,3,3) #Gaussian random numbers

3×3×3 Array{Float64, 3}:
[:, :, 1] =
 -0.406652   0.370825  -0.875568
 -0.0911162  0.912426  -0.183093
  0.885836   0.802659  -1.28124

[:, :, 2] =
  0.673902  -0.395175  -0.0552175
  0.272535   0.4158    -0.637409
 -1.38995   -0.333023   0.640275

[:, :, 3] =
 0.222694  0.201205  -0.50176
 0.982581  0.1885     0.326771
 0.784697  0.583346  -0.331677

In [23]:
a = rand(10,10)
minm = minimum(a)
maxm = maximum(a)
minm, maxm = extrema(a)

(0.010956009885386808, 0.9950141006535137)

In [27]:
using Statistics
a = rand(30) #rand(30,)
b = mean(a)

0.4725820334972539

In [28]:
a = rand(5, 5)
b = zeros(Float64, size(a,1) + 2, size(a,2) + 2) # b = zeros(eltype(a), size(a) .+1)
b[2:end-1, 2:end-1] = a

5×5 Matrix{Float64}:
 0.0086558  0.66705   0.580562  0.237475   0.22059
 0.380458   0.831228  0.919756  0.135894   0.343454
 0.931539   0.451081  0.208204  0.480797   0.535672
 0.705826   0.135295  0.87461   0.0525574  0.757232
 0.302244   0.301708  0.623066  0.813865   0.256428

In [31]:
a = Bidiagonal(zeros(5,), collect(1:4), :L)

5×5 Bidiagonal{Float64, Vector{Float64}}:
 0.0   ⋅    ⋅    ⋅    ⋅ 
 1.0  0.0   ⋅    ⋅    ⋅ 
  ⋅   2.0  0.0   ⋅    ⋅ 
  ⋅    ⋅   3.0  0.0   ⋅ 
  ⋅    ⋅    ⋅   4.0  0.0

In [32]:
a = zeros(Int64, 8, 8)
a[1:2:end, 1:2:end] .= 1
a[2:2:end, 2:2:end] .= 1 #or
a = [Int(isodd(i+j)) for i in 1:8, j in 1:8]

8×8 Matrix{Int64}:
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0

In [35]:
m = 100
n, p, r = 6, 7, 8
page = Int64(ceil(m/n/p))
col = Int64(ceil((m-(page-1)*n*p)/n))
row = Int64(ceil((m-(page-1)*n*p-(col-1)*n)/n))

CartesianIndices((6, 7, 8))[m] #builtin command

CartesianIndex(4, 3, 3)

In [36]:
repeat([1 0;0 1], 4, 4)

8×8 Matrix{Int64}:
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1

In [37]:
a = randn(5, 5)
a = a .- minimum(a)
a = a./maximum(a)

5×5 Matrix{Float64}:
 0.281285  0.231453   0.0       0.570824  0.552566
 0.605775  0.313041   0.643971  0.263395  0.870787
 0.566585  0.922843   0.22214   0.668521  0.358981
 0.418636  0.0514331  0.244294  1.0       0.00795952
 0.363396  0.644681   0.44372   0.37264   0.583651

In [39]:
mutable struct color
    R::UInt8
    G::UInt8
    B::UInt8
    A::UInt8
end

In [40]:
a = rand(5, 3); b = rand(3, 2)
c = a*b

5×2 Matrix{Float64}:
 0.304558   0.449231
 0.13708    0.361946
 0.0702985  0.256702
 0.451667   0.884323
 0.243583   0.274758

In [42]:
a = 3;b = 8;
x = rand(1:10,20) # collect(1:10)
x[a .<= x .<= b] .= -x[a .<= x .<= b] #or
x[a .<= x .<= b] .*= -1.

0-element view(::Vector{Int64}, Int64[]) with eltype Int64

In [45]:
round.(-4.5, RoundNearestTiesAway)

-5.0

In [48]:
using Dates
tod = today()
tom = tod + Day(1)
yes = tod + Day(-1)

2022-07-29

In [49]:
using Dates
mon = collect(Date(1988,3,1):Day(1):Date(1988, 3, 21))

21-element Vector{Date}:
 1988-03-01
 1988-03-02
 1988-03-03
 1988-03-04
 1988-03-05
 1988-03-06
 1988-03-07
 1988-03-08
 1988-03-09
 1988-03-10
 1988-03-11
 1988-03-12
 1988-03-13
 1988-03-14
 1988-03-15
 1988-03-16
 1988-03-17
 1988-03-18
 1988-03-19
 1988-03-20
 1988-03-21

In [50]:
A = rand(2, 2); B = rand(2, 2)
@. A = ((A+B)*(-A/2))

2×2 Matrix{Float64}:
 -0.112221  -0.0198014
 -0.277931  -0.0962351

In [52]:
A = 10*rand(1,10)
Int64.(trunc.(A))
B = parse.(Int64,[split(string(x),".")[1] for x in A])
Int64.(floor.(A))
Int64.(ceil.(A)) .- 1

1×10 Matrix{Int64}:
 1  8  1  5  8  3  8  6  3  5

In [53]:
a = rand(0:4,5,5)

5×5 Matrix{Int64}:
 4  4  1  4  0
 2  2  0  0  4
 2  0  1  4  2
 1  3  0  4  2
 0  4  1  1  2

In [54]:
a = collect(1:10)

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [55]:
a = rand(10)

10-element Vector{Float64}:
 0.448588370907255
 0.5740094326683145
 0.7266209319446986
 0.5654013800239049
 0.2526783612283935
 0.13092193841888444
 0.017564553494533675
 0.13657452543017035
 0.07888338188348176
 0.9384275492157458

In [56]:
a = rand(10,)
sort!(a)

10-element Vector{Float64}:
 0.003941988424243759
 0.3130359436311789
 0.37781410024011974
 0.4051332436659988
 0.5410943184610901
 0.5439534156110188
 0.6562682270970318
 0.7344709597520325
 0.9693050950784624
 0.9744010200754359

In [57]:
isequal(A,B)

false

In [58]:
a = rand(10,2);
ang = angle.(a[:,1] .+ 1im*a[:,2])
r = hypot.(a[:,1] .+ a[:,2])# sqrt.(a[:,1].^2 .+ a[:,2].^2)
p = r.*cis.(ang)  # r.*exp.(1im*ang) 
#or
to_polar(x, y) = hypot(x, y) * cis(angle(x+im*y))
[to_polar(x...) for x in eachrow(a)] #or
[to_polar(a[i, 1], a[i, 2]) for i in axes(a, 1)] 

10-element Vector{ComplexF64}:
  0.4065084607605163 + 0.6511362976926275im
   0.990886559671946 + 0.5943931444808569im
  0.2263629451463699 + 0.39439731669920597im
 0.39940347588389147 + 0.5668815666992407im
 0.23788753107635416 + 0.395049314391114im
  0.7590185970233304 + 0.17488862671047278im
 0.17089881248978936 + 0.943126881106473im
  0.8071373042682866 + 0.27466669972730606im
  0.1414363132638586 + 0.6862513085223453im
  0.7947217163100571 + 0.6707730591286355im

In [59]:
a = rand(10)
a[a .==  maximum(a)] .= 0

1-element view(::Vector{Float64}, [9]) with eltype Float64:
 0.0

In [63]:
X = rand(5);Y = rand(5);
C = [1/(xi-yi) for xi in X, yi in Y]#or
C = 1 ./ (X .- Y')

5×5 Matrix{Float64}:
 159.266     -7.98849   3.10236   11.5602   -32.2646
 -13.6612    -4.88618   4.11767  142.354     -9.05202
  -3.70474   -2.49139  21.677     -5.2715    -3.25524
  13.9018   -16.7994    2.57739    6.57212   28.8511
  -2.07016   -1.6273   -5.98808   -2.48244   -1.92187

In [66]:
print(a)
display(a)
foreach(println, a) #prints full array

[0.9285185394752822, 0.3217035373304292, 0.6578265166355485, 0.8578393515606015, 0.7596003511679978, 0.1946976091483914, 0.35299627786900145, 0.8331590921392543, 0.0, 0.20168450204254484]

10-element Vector{Float64}:
 0.9285185394752822
 0.3217035373304292
 0.6578265166355485
 0.8578393515606015
 0.7596003511679978
 0.1946976091483914
 0.35299627786900145
 0.8331590921392543
 0.0
 0.20168450204254484

0.9285185394752822
0.3217035373304292
0.6578265166355485
0.8578393515606015
0.7596003511679978
0.1946976091483914
0.35299627786900145
0.8331590921392543
0.0
0.20168450204254484


In [67]:
a = rand(10)
x = 0.5 #given scalar
b = abs.(a .- x)
a[findmin(b)[2]]

0.4829332691073728